apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webpage-@color@
spec:
  replicas: 3
  template:
    metadata:
      labels:
        color: @color@
    spec:
      containers:
      - name: bgdemo
        image: mycluster.icp:8500/devops/bgdemo:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
