apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-@color@
  labels:
    app: bgdemo
    color: @color@
spec:
  selector:
    matchLabels:
      app: bgdemo
      color: @color@
  replicas: 1
  template:
    metadata:
      labels:
        app: bgdemo
        color: @color@
    spec:
      containers:
      - name: bgdemo
        image: mycluster.icp:8500/devops/bgdemo:v1
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: NAME
          value: IIF
        - name: backgroundcolor
          value: @background-color@
        - name: version
          value @version@
        - name: env
          value @env@  
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-dev
  labels:
    app: bgdemo
    color: @color@
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: bgdemo
    color: @color@


