node {
    dir("/root/"){
    checkout scm

    env.DOCKER_API_VERSION="1.23"
    appName = "devops/bgdemo"
    registryHost = "mycluster.icp:8500/"
    imageName = "${registryHost}${appName}:${env.BUILD_ID}"
    env.BUILDIMG=imageName
    docker.withRegistry('https://mycluster.icp:8500/', 'docker'){
    stage "Build"

        def pcImg = docker.build("mycluster.icp:8500/devops/bgdemo:${env.BUILD_ID}", "-f Dockerfile.ppc64le .")
        sh "cp /root/.docker/config.json ${HOME}/.docker/config.json"
        pcImg.push()
     
       }
    } 
}
