apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-@@@env@@@
  labels:
    app: bgdemo
    env: @@@env@@@
spec:
  selector:
    matchLabels:
      app: bgdemo
      env: @@@env@@@
  replicas: 3
  template:
    metadata:
      labels:
        app: bgdemo
        env: @@@env@@@
    spec:
      containers:
      - name: bgdemo
        image: {{ .Values.image.repository }}/devops/bgdemo:{{ .Values.image.tag }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: NAME
          value: IIF
        - name: backgroundcolor
          value: @@@background-color@@@
        - name: env
          value: {{ .Values.helloname }}  
        ports:
        - containerPort: 80
