apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-@@@env@@@
  labels:
    app: bgdemohelm
    env: @@@env@@@
spec:
  selector:
    matchLabels:
      app: bgdemohelm
      env: @@@env@@@
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: bgdemohelm
        env: @@@env@@@
    spec:
      containers:
      - name: bgdemohelm
        image: {{ .Values.image.repository }}/devops/bgdemohelm:{{ .Values.image.tag }}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: NAME
          value: IIF
        - name: backgroundcolor
          value: @@@background-color@@@
        - name: env
          value: {{ .Values.helloname }}  
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: bgdemohelm-service-@env@
  labels:
    app: bgdemohelm
    env: @@@env@@@
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: bgdemohelm
    env: @@@env@@@
